# Generated by Django 5.2.3 on 2025-06-25 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الصنف العربي')),
                ('name_en', models.CharField(max_length=255, verbose_name='اسم الصنف الإنجليزي')),
                ('agent', models.CharField(max_length=255, verbose_name='الوكيل')),
                ('show_agent', models.BooleanField(default=True, verbose_name='عرض الوكيل')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='الشركة المنتجة')),
                ('show_manufacturer', models.BooleanField(default=True, verbose_name='عرض الشركة المنتجة')),
                ('country_of_origin', models.CharField(max_length=255, verbose_name='بلد التصنيع')),
                ('show_country_of_origin', models.BooleanField(default=True, verbose_name='عرض بلد التصنيع')),
                ('scientific_name', models.CharField(max_length=255, verbose_name='الاسم العلمي')),
                ('show_scientific_name', models.BooleanField(default=True, verbose_name='عرض الاسم العلمي')),
                ('usage', models.TextField(verbose_name='دواعي الاستعمال')),
                ('show_usage', models.BooleanField(default=True, verbose_name='عرض دواعي الاستعمال')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('show_price', models.BooleanField(default=True, verbose_name='عرض السعر')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drug_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='drugs.drugcategory', verbose_name='الفئة')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='drugs.drugunits')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='drugs.drug')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drugs.order')),
            ],
        ),
    ]
