# Generated by Django 5.2.3 on 2025-06-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='show_expiry_date',
            field=models.BooleanField(default=True, verbose_name='عرض تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوكيل'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بلد التصنيع'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الشركة المنتجة'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم العلمي'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='usage',
            field=models.TextField(blank=True, null=True, verbose_name='دواعي الاستعمال'),
        ),
    ]
