# Generated by Django 5.2.3 on 2025-06-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_drug_show_expiry_date_alter_drug_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='drug',
            name='show_description',
            field=models.BooleanField(default=True, verbose_name='عرض الوصف'),
        ),
    ]
