# Generated by Django 5.2.3 on 2025-07-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم الصنف الإنجليزي'),
        ),
    ]
