# Generated by Django 5.2.3 on 2025-07-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان التحديث')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('version', models.CharField(max_length=100, verbose_name='الاصدار')),
                ('file', models.FileField(upload_to='updates/', verbose_name='الملف')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
